#!/bin/sh

#VERBOSE="-v"
cd /home/athan/public_html/games/elite-dangerous/fd-api && ( \
find docs -name \*.html -exec chmod ${VERBOSE} go+r {} \;
find org \( -name \*.py -o \( -type d -a \! -name __pycache__ \) \) -exec chmod ${VERBOSE} og+rX {} \;
chmod ${VERBOSE} go+r \
	*.html
chmod ${VERBOSE} 644 fd-api-config.yaml
chmod ${VERBOSE} 700 fd-ed-capi.py
chmod ${VERBOSE} 755 oauth2-pkce.py

exit $?
)
exit $?

